language: php
php: 5.6
before_script:
    - composer install
    - mysql -e 'CREATE DATABASE `reen`;'
    - mysql -e 'UPDATE user SET password=PASSWORD('empty') WHERE user='root';'

env:
    - DB=mysql

script:
    - run_tests.sh