<?php

namespace AppBundle\Repository;

use AppBundle\Common\ExistIdListInterface;

/**
 * SCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SCityRepository extends \Doctrine\ORM\EntityRepository implements ExistIdListInterface
{
    use ExistIdListRepositoryTrait;

    public function getNameList(array $idList)
    {
        $source = $this->createQueryBuilder('c')
            ->select('c.name')
            ->where('c.id IN (:idList)')
            ->setParameter('idList', $idList)
            ->getQuery()
            ->getResult();

        return array_column($source, 'name');
    }
}
