<?php

namespace AppBundle\Repository;

/**
 * SCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SCityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNameList($idList)
    {
        $source = $this->createQueryBuilder('c')
            ->select('c.name')
            ->where('c.id IN (:idList)')
            ->setParameter('idList', $idList)
            ->getQuery()
            ->getArrayResult();

        return array_column($source, 'name');
    }
}
