<?php

namespace AppBundle\Repository;

/**
 * SCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SCityRepository extends \Doctrine\ORM\EntityRepository
{
}
