<?php

namespace AppBundle\Repository;

/**
 * SDeveloperProfileToSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SDeveloperProfileToSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
