<?php

namespace AppBundle\Repository;

/**
 * SDeveloperProfileToSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SDeveloperProfileToSkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSkillIdList()
    {
        $source = $this
            ->createQueryBuilder('dp2s')
            ->distinct(true)
            ->select('dp2s.skillId')
            ->getQuery()
            ->getResult();

        return array_column($source, 'skillId');
    }
}
