<?php

namespace AppBundle\Repository;

use AppBundle\Searcher\DevelopProfileParameter;
use Doctrine\ORM\QueryBuilder;

/**
 * SDeveloperProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SDeveloperProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function search(DevelopProfileParameter $developProfileParameter)
    {
        $queryBuilder = $this->createQueryBuilder('dp');

        $this->useSearchParameter($queryBuilder, $developProfileParameter);

        return $queryBuilder
            ->getQuery()
            ->getResult();
    }

    private function useSearchParameter(QueryBuilder $queryBuilder, DevelopProfileParameter $developProfileParameter)
    {
        if ($skillBitSetPattern = $developProfileParameter->getSkillBitSetPattern()) {
            $queryBuilder
                ->join('dp.searchParameter', 'sp')
                ->andWhere('sp.skillBitSet LIKE :skillBitSetPattern')
                ->setParameter('skillBitSetPattern', $skillBitSetPattern);
        }
    }
}
