<?php

namespace AppBundle\Repository;

/**
 * SDeveloperProfileSearchParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SDeveloperProfileSearchParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
