<?php

namespace AppBundle\Repository;

/**
 * SSKillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SSKillRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllLike($value)
    {

    }
}
