<?php

namespace AppBundle\Repository;

use AppBundle\Common\ExistIdListInterface;

/**
 * SSKillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SSKillRepository extends \Doctrine\ORM\EntityRepository implements ExistIdListInterface
{
    use ExistIdListRepositoryTrait;

    public function findAllLike($value)
    {
        $list = $this
            ->createQueryBuilder('s')
            ->select('s.name')
            ->where('s.name LIKE :value')
            ->setParameter('value', "%$value%")
            ->getQuery()
            ->getResult();

        return array_column($list, 'name');
    }

    public function exists($name)
    {
        return (bool)$this->createQueryBuilder('s')
            ->select('1')
            ->where('s.name = :name')
            ->setParameter('name', $name)
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function getIdList(array $names)
    {
        $source = $this->createQueryBuilder('s')
            ->select('s.id')
            ->where('s.name IN (:names)')
            ->setParameter('names', $names)
            ->getQuery()
            ->getArrayResult();

        return array_column($source, 'id');
    }

    public function getNameList(array $idList)
    {
        $source = $this->createQueryBuilder('s')
            ->select('s.name')
            ->where('s.id IN (:idList)')
            ->setParameter('idList', $idList)
            ->getQuery()
            ->getArrayResult();

        return array_column($source, 'name');
    }
}
