<?php

namespace AppBundle\Repository;

/**
 * SUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SUserRepository extends \Doctrine\ORM\EntityRepository
{
}
