developers:
    path: /developers.{_format}
    defaults: { _controller: AppBundle:Api/Developer:list }
    requirements:
        _method: GET
        _format: json

filters:
    path: /filters.{_format}
    defaults: { _controller: AppBundle:Api/Filter:list }
    requirements:
        _method: GET
        _format: json