services:
    rqs.skill:
        class: AppBundle\Services\SkillService
        arguments:
            - '@doctrine'

    rqs.developer_profile:
        class: AppBundle\Services\DeveloperProfileService
        arguments:
            - '@doctrine'

    rqs.user:
        class: AppBundle\Services\UserService
        arguments:
            - '@doctrine'