services:
    rqs.skill:
        class: AppBundle\Service\SkillService
        arguments:
            - '@doctrine'

    rqs.developer_profile:
        class: AppBundle\Service\DeveloperProfileService
        arguments:
            - '@doctrine'

    rqs.user:
        class: AppBundle\Service\UserService
        arguments:
            - '@doctrine'