services:
    rqs.skill:
        class: AppBundle\Service\SkillService
        arguments:
            - '@doctrine'

    rqs.developer_profile:
        class: AppBundle\Service\DeveloperProfileService
        arguments:
            - '@doctrine'

    rqs.developer.searcher:
        class: AppBundle\Service\DeveloperSearcherService

    rqs.user:
        class: AppBundle\Service\UserService
        arguments:
            - '@doctrine'

    rqs.database.tester:
        class: AppBundle\Service\DatabaseTesterService
        arguments:
            - '@doctrine'