services:
    rqs.skill:
        class: AppBundle\Service\SkillService
        arguments:
            - '@doctrine'

    rqs.developer_profile:
        class: AppBundle\Service\DeveloperProfileService
        arguments:
            - '@doctrine'

    rqs.developer.profile.parameter.parser:
        class: AppBundle\Service\DeveloperSearchParameterParser

    rqs.developer.searcher:
        class: AppBundle\Service\DeveloperSearcherService
        arguments:
            - '@doctrine'
            - '@rqs.developer.profile.parameter.parser'

    rqs.user:
        class: AppBundle\Service\UserService
        arguments:
            - '@doctrine'

    rqs.database.tester:
        class: AppBundle\Service\DatabaseTesterService
        arguments:
            - '@doctrine'