services:
    rqs.skill:
        class: AppBundle\Service\SkillService
        arguments:
            - '@doctrine'

    rqs.city:
        class: AppBundle\Service\CityService
        arguments:
            - '@doctrine'

    rqs.developer.profile.search.parameter:
        class: AppBundle\Service\DevelopProfile\SearchParameterService

    rqs.developer.profile:
        class: AppBundle\Service\DeveloperProfileService
        arguments:
            - '@doctrine'
            - '@rqs.developer.profile.search.parameter'

    rqs.developer.profile.parameter.parser:
        class: AppBundle\Service\DeveloperSearchParameterParser
        arguments:
            - '@rqs.developer.profile.search.parameter'
            - '@rqs.skill'
            - '@rqs.city'

    rqs.developer.profile.parameter.doctrine.criteria.provider:
        class: AppBundle\Service\DevelopProfile\Doctrine\CriteriaProvider
        arguments:
            - '@doctrine'

    rqs.developer.profile.parameter:
        class: AppBundle\Service\DeveloperSearchParameterService
        arguments:
            - '@rqs.developer.profile.parameter.doctrine.criteria.provider'

    rqs.developer.searcher.factory:
        class: AppBundle\Service\DeveloperSearcherFactory
        arguments:
            - '@doctrine'

    rqs.developer.concrete.searcher:
        class: AppBundle\Service\DevelopProfile\SearchServiceInterface
        factory: ['@rqs.developer.searcher.factory', createSearcher]

    rqs.developer.searcher:
        class: AppBundle\Service\DeveloperSearcherService
        arguments:
            - '@rqs.developer.concrete.searcher'
            - '@rqs.developer.profile.parameter.parser'

    rqs.user:
        class: AppBundle\Service\UserService
        arguments:
            - '@doctrine'

    rqs.database.tester:
        class: AppBundle\Service\DatabaseTesterService
        arguments:
            - '@doctrine'