AppBundle\Entity\SCity:
    type: entity
    table: s_city
    repositoryClass: AppBundle\Repository\SCityRepository

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false