AppBundle\Entity\SDeveloperProfileToSkill:
    type: entity
    table: s_developer_profile_to_skill
    repositoryClass: AppBundle\Repository\SDeveloperProfileToSkillRepository

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY

    manyToOne:
        developerProfile:
            targetEntity: AppBundle\Entity\SDeveloperProfile
            fetch: EXTRA_LAZY
            joinColumn:
                name: developer_id
                referencedColumnName: id
        skill:
            targetEntity: AppBundle\Entity\SSKill
            fetch: EXTRA_LAZY
            joinColumn:
                name: skill_id
                referencedColumnName: id

    fields:
        position:
            type: integer
        score:
            type: integer
