AppBundle\Entity\SDeveloperProfile:
    type: entity
    table: s_developer_profile
    repositoryClass: AppBundle\Repository\SDeveloperProfileRepository

    manyToOne:
        user:
            targetEntity: AppBundle\Entity\SUser
            inversedBy: developerProfiles
            joinColumn:
                name: user_id
                referencedColumnName: id
            fetch: EXTRA_LAZY

    oneToMany:
        skills:
            targetEntity: AppBundle\Entity\SDeveloperProfileToSkill
            mappedBy: developerProfile
            fetch: EXTRA_LAZY

    oneToOne:
        searchParameter:
            targetEntity: AppBundle\Entity\SDeveloperProfileSearchParameter
            mappedBy: developerProfile
            fetch: EXTRA_LAZY

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        title:
            type: string
            nullable: false
            length: 255
        salary:
            type: integer
            nullable: false
        description:
            type: string
            nullable: false
