AppBundle\Entity\SDeveloperProfile:
    type: entity
    table: s_developer_profile
    repositoryClass: AppBundle\Repository\SDeveloperProfileRepository

    manyToMany:
        skills:
            targetEntity: AppBundle\Entity\SSKill
            fetch: EXTRA_LAZY
            joinTable:
                name: s_developer_to_skill
                joinColumns:
                    developer_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    skill_id:
                        referencedColumnName: id

    manyToOne:
        user:
            targetEntity: AppBundle\Entity\SUser
            inversedBy: developerProfiles
            joinColumn:
                name: user_id
                referencedColumnName: id
            fetch: EXTRA_LAZY

    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY

    fields:
        title:
            type: string
            nullable: false
            length: 255
        salary:
            type: integer
            nullable: false
        description:
            type: string
            nullable: false
